export const cities=
    [{ label: 'Adilabad', state: 'Andhra Pradesh (AP)' },
    { label: 'Anantapur', state: 'Andhra Pradesh (AP)' },
    { label: 'Chittoor', state: 'Andhra Pradesh (AP)' },
    { label: 'Kakinada', state: 'Andhra Pradesh (AP)' },
    { label: 'Guntur', state: 'Andhra Pradesh (AP)' },
    { label: 'Hyderabad', state: 'Andhra Pradesh (AP)' },
    { label: 'Krishna', state: 'Andhra Pradesh (AP)' },
    { label: 'Kurnool', state: 'Andhra Pradesh (AP)' },
    { label: 'Medak', state: 'Andhra Pradesh (AP)' },
    { label: 'Nalgonda', state: 'Andhra Pradesh (AP)' },
    { label: 'Ongole', state: 'Andhra Pradesh (AP)' },
    { label: 'Srikakulam', state: 'Andhra Pradesh (AP)' },
    { label: 'Nellore', state: 'Andhra Pradesh (AP)' },
    { label: 'Visakhapatnam', state: 'Andhra Pradesh (AP)' },
    { label: 'Vizianagaram', state: 'Andhra Pradesh (AP)' },
    { label: 'Eluru', state: 'Andhra Pradesh (AP)' },
    { label: 'Kadapa', state: 'Andhra Pradesh (AP)' },
    { label: 'Anjaw', state: 'Arunachal Pradesh (AR)' },
    { label: 'Changlang', state: 'Arunachal Pradesh (AR)' },
    { label: 'East Siang', state: 'Arunachal Pradesh (AR)' },
    { label: 'Kurung Kumey', state: 'Arunachal Pradesh (AR)' },
    { label: 'Lohit', state: 'Arunachal Pradesh (AR)' },
    { label: 'Lower Dibang Valley', state: 'Arunachal Pradesh (AR)' },
    { label: 'Lower Subansiri', state: 'Arunachal Pradesh (AR)' },
    { label: 'Papum Pare', state: 'Arunachal Pradesh (AR)' },
    { label: 'Tawang', state: 'Arunachal Pradesh (AR)' },
    { label: 'Tirap', state: 'Arunachal Pradesh (AR)' },
    { label: 'Dibang Valley', state: 'Arunachal Pradesh (AR)' },
    { label: 'Upper Siang', state: 'Arunachal Pradesh (AR)' },
    { label: 'Upper Subansiri', state: 'Arunachal Pradesh (AR)' },
    { label: 'West Kameng', state: 'Arunachal Pradesh (AR)' },
    { label: 'West Siang', state: 'Arunachal Pradesh (AR)' },
    { label: 'Baksa', state: 'Assam (AS)' },
        { label: 'Barpeta', state: 'Assam (AS)' },
        { label: 'Bongaigaon', state: 'Assam (AS)' },
        { label: 'Cachar', state: 'Assam (AS)' },
        { label: 'Chirang', state: 'Assam (AS)' },
        { label: 'Darrang', state: 'Assam (AS)' },
        { label: 'Dhemaji', state: 'Assam (AS)' },
        { label: 'Dima Hasao', state: 'Assam (AS)' },
        { label: 'Dhubri', state: 'Assam (AS)' },
        { label: 'Dibrugarh', state: 'Assam (AS)' },
        { label: 'Goalpara', state: 'Assam (AS)' },
        { label: 'Golaghat', state: 'Assam (AS)' },
        { label: 'Hailakandi', state: 'Assam (AS)' },
        { label: 'Jorhat', state: 'Assam (AS)' },
        { label: 'Kamrup', state: 'Assam (AS)' },
        { label: 'Kamrup Metropolitan', state: 'Assam (AS)' },
        { label: 'Karbi Anglong', state: 'Assam (AS)' },
        { label: 'Karimganj', state: 'Assam (AS)' },
        { label: 'Kokrajhar', state: 'Assam (AS)' },
        { label: 'Lakhimpur', state: 'Assam (AS)' },
        { label: 'Marigaon', state: 'Assam (AS)' },
        { label: 'Nagaon', state: 'Assam (AS)' },
        { label: 'Nalbari', state: 'Assam (AS)' },
        { label: 'Sibsagar', state: 'Assam (AS)' },
        { label: 'Sonitpur', state: 'Assam (AS)' },
        { label: 'Tinsukia', state: 'Assam (AS)' },
        { label: 'Udalguri', state: 'Assam (AS)' },
        { label: 'Araria', state: 'Bihar (BR)' },
        { label: 'Arwal', state: 'Bihar (BR)' },
        { label: 'Aurangabad', state: 'Bihar (BR)' },
        { label: 'Banka', state: 'Bihar (BR)' },
        { label: 'Begusarai', state: 'Bihar (BR)' },
        { label: 'Bhagalpur', state: 'Bihar (BR)' },
        { label: 'Bhojpur', state: 'Bihar (BR)' },
        { label: 'Buxar', state: 'Bihar (BR)' },
        { label: 'Darbhanga', state: 'Bihar (BR)' },
        { label: 'East Champaran', state: 'Bihar (BR)' },
        { label: 'Gaya', state: 'Bihar (BR)' },
        { label: 'Gopalganj', state: 'Bihar (BR)' },
        { label: 'Jamui', state: 'Bihar (BR)' },
        { label: 'Jehanabad', state: 'Bihar (BR)' },
        { label: 'Kaimur', state: 'Bihar (BR)' },
        { label: 'Katihar', state: 'Bihar (BR)' },
        { label: 'Khagaria', state: 'Bihar (BR)' },
        { label: 'Kishanganj', state: 'Bihar (BR)' },
        { label: 'Lakhisarai', state: 'Bihar (BR)' },
        { label: 'Madhepura', state: 'Bihar (BR)' },
        { label: 'Madhubani', state: 'Bihar (BR)' },
        { label: 'Muzaffarpur', state: 'Bihar (BR)' },
        { label: 'Nalanda', state: 'Bihar (BR)' },
        { label: 'Nawada', state: 'Bihar (BR)' },
        { label: 'Patna', state: 'Bihar (BR)' },
        { label: 'Purnia', state: 'Bihar (BR)' },
        { label: 'Rohtas', state: 'Bihar (BR)' },
        { label: 'West Champaran', state: 'Bihar (BR)' },
        { label: 'Vaishali', state: 'Bihar (BR)' },
        { label: 'Supaul', state: 'Bihar (BR)' },
        { label: 'Siwan', state: 'Bihar (BR)' },
        { label: 'Sitamarhi', state: 'Bihar (BR)' },
        { label: 'Sheohar', state: 'Bihar (BR)' },
        { label: 'Sheikhpura', state: 'Bihar (BR)' },
        { label: 'Saran', state: 'Bihar (BR)' },
        { label: 'Samastipur', state: 'Bihar (BR)' },
        { label: 'Saharsa', state: 'Bihar (BR)' },
        { label: 'Chandigarh', state: 'Bihar (BR)' },
        { label: 'Bastar', state: 'Chhattisgarh (CG)' },
        { label: 'Bijapur', state: 'Chhattisgarh (CG)' },
        { label: 'Bilaspur', state: 'Chhattisgarh (CG)' },
        { label: 'Dantewada', state: 'Chhattisgarh (CG)' },
        { label: 'Dhamtari', state: 'Chhattisgarh (CG)' },
        { label: 'Durg', state: 'Chhattisgarh (CG)' },
        { label: 'Jashpur', state: 'Chhattisgarh (CG)' },
        { label: 'Janjgir-Champa', state: 'Chhattisgarh (CG)' },
        { label: 'Korba', state: 'Chhattisgarh (CG)' },
        { label: 'Koriya', state: 'Chhattisgarh (CG)' },
        { label: 'Kanker', state: 'Chhattisgarh (CG)' },
        { label: 'Kabirdham (Kawardha)', state: 'Chhattisgarh (CG)' },
        { label: 'Mahasamund', state: 'Chhattisgarh (CG)' },
        { label: 'Narayanpur', state: 'Chhattisgarh (CG)' },
        { label: 'Raigarh', state: 'Chhattisgarh (CG)' },
        { label: 'Rajnandgaon', state: 'Chhattisgarh (CG)' },
        { label: 'Raipur', state: 'Chhattisgarh (CG)' },
        { label: 'Surguja', state: 'Chhattisgarh (CG)' },
        { label: 'Dadra and Nagar Haveli', state: 'Dadra and Nagar Haveli (DN)' },
        { label: 'Daman', state: 'Daman and Diu (DD)' },
        { label: 'Diu', state: 'Daman and Diu (DD)' },
        { label: 'West Delhi', state: 'Delhi (DL)' },
        { label: 'North Goa', state: 'Goa (GA)' },
        { label: 'South Goa', state: 'Goa (GA)' },
        { label: 'Ahmedabad', state: 'Gujarat (GJ)' },
        { label: 'Amreli district', state: 'Gujarat (GJ)' },
        { label: 'Anand', state: 'Gujarat (GJ)' },
        { label: 'Banaskantha', state: 'Gujarat (GJ)' },
        { label: 'Bharuch', state: 'Gujarat (GJ)' },
        { label: 'Bhavnagar', state: 'Gujarat (GJ)' },
        { label: 'Dahod', state: 'Gujarat (GJ)' },
        { label: 'The Dangs', state: 'Gujarat (GJ)' },
        { label: 'Gandhinagar', state: 'Gujarat (GJ)' },
        { label: 'Jamnagar', state: 'Gujarat (GJ)' },
        { label: 'Junagadh', state: 'Gujarat (GJ)' },
        { label: 'Kutch', state: 'Gujarat (GJ)' },
        { label: 'Kheda', state: 'Gujarat (GJ)' },
        { label: 'Mehsana', state: 'Gujarat (GJ)' },
        { label: 'Narmada', state: 'Gujarat (GJ)' },
        { label: 'Navsari', state: 'Gujarat (GJ)' },
        { label: 'Patan', state: 'Gujarat (GJ)' },
        { label: 'Panchmahal', state: 'Gujarat (GJ)' },
        { label: 'Porbandar', state: 'Gujarat (GJ)' },
        { label: 'Rajkot', state: 'Gujarat (GJ)' },
        { label: 'Sabarkantha', state: 'Gujarat (GJ)' },
        { label: 'Surendranagar', state: 'Gujarat (GJ)' },
        { label: 'Surat', state: 'Gujarat (GJ)' },
        { label: 'Vyara', state: 'Gujarat (GJ)' },
        { label: 'Vadodara', state: 'Gujarat (GJ)' },
        { label: 'Valsad', state: 'Gujarat (GJ)' },
        { label: 'Ambala', state: 'Haryana (HR)' },
        { label: 'Bhiwani', state: 'Haryana (HR)' },
        { label: 'Faridabad', state: 'Haryana (HR)' },
        { label: 'Fatehabad', state: 'Haryana (HR)' },
        { label: 'Gurgaon', state: 'Haryana (HR)' },
        { label: 'Hissar', state: 'Haryana (HR)' },
        { label: 'Jhajjar', state: 'Haryana (HR)' },
        { label: 'Jind', state: 'Haryana (HR)' },
        { label: 'Karnal', state: 'Haryana (HR)' },
        { label: 'Kaithal', state: 'Haryana (HR)' },
        { label: 'Kurukshetra', state: 'Haryana (HR)' },
        { label: 'Mahendragarh', state: 'Haryana (HR)' },
        { label: 'Mewat', state: 'Haryana (HR)' },
        { label: 'Palwal', state: 'Haryana (HR)' },
        { label: 'Panchkula', state: 'Haryana (HR)' },
        { label: 'Panipat', state: 'Haryana (HR)' },
        { label: 'Rewari', state: 'Haryana (HR)' },
        { label: 'Rohtak', state: 'Haryana (HR)' },
        { label: 'Sirsa', state: 'Haryana (HR)' },
        { label: 'Sonipat', state: 'Haryana (HR)' },
        { label: 'Yamuna Nagar', state: 'Haryana (HR)' },
        { label: 'Bilaspur', state: 'Himachal Pradesh (HP)' },
        { label: 'Chamba', state: 'Himachal Pradesh (HP)' },
        { label: 'Hamirpur', state: 'Himachal Pradesh (HP)' },
        { label: 'Kangra', state: 'Himachal Pradesh (HP)' },
        { label: 'Kinnaur', state: 'Himachal Pradesh (HP)' },
        { label: 'Kullu', state: 'Himachal Pradesh (HP)' },
        { label: 'Lahaul and Spiti', state: 'Himachal Pradesh (HP)' },
        { label: 'Mandi', state: 'Himachal Pradesh (HP)' },
        { label: 'Shimla', state: 'Himachal Pradesh (HP)' },
        { label: 'Sirmaur', state: 'Himachal Pradesh (HP)' },
        { label: 'Solan', state: 'Himachal Pradesh (HP)' },
        { label: 'Una', state: 'Himachal Pradesh (HP)' },
        { label: 'Anantnag', state: 'Jammu and Kashmir (JK)' },
        { label: 'Badgam', state: 'Jammu and Kashmir (JK)' },
        { label: 'Bandipora', state: 'Jammu and Kashmir (JK)' },
        { label: 'Baramulla', state: 'Jammu and Kashmir (JK)' },
        { label: 'Doda', state: 'Jammu and Kashmir (JK)' },
        { label: 'Ganderbal', state: 'Jammu and Kashmir (JK)' },
        { label: 'Jammu', state: 'Jammu and Kashmir (JK)' },
        { label: 'Kargil', state: 'Jammu and Kashmir (JK)' },
        { label: 'Kathua', state: 'Jammu and Kashmir (JK)' },
        { label: 'Kishtwar', state: 'Jammu and Kashmir (JK)' },
        { label: 'Kupwara', state: 'Jammu and Kashmir (JK)' },
        { label: 'Kulgam', state: 'Jammu and Kashmir (JK)' },
        { label: 'Leh', state: 'Jammu and Kashmir (JK)' },
        { label: 'Poonch', state: 'Jammu and Kashmir (JK)' },
        { label: 'Pulwama', state: 'Jammu and Kashmir (JK)' },
        { label: 'Rajauri', state: 'Jammu and Kashmir (JK)' },
        { label: 'Ramban', state: 'Jammu and Kashmir (JK)' },
        { label: 'Reasi', state: 'Jammu and Kashmir (JK)' },
        { label: 'Samba', state: 'Jammu and Kashmir (JK)' },
        { label: 'Shopian', state: 'Jammu and Kashmir (JK)' },
        { label: 'Srinagar', state: 'Jammu and Kashmir (JK)' },
        { label: 'Udhampur', state: 'Jammu and Kashmir (JK)' },
        { label: 'Bokaro', state: 'Jharkhand (JH)' },
        { label: 'Chatra', state: 'Jharkhand (JH)' },
        { label: 'Deoghar', state: 'Jharkhand (JH)' },
        { label: 'Dhanbad', state: 'Jharkhand (JH)' },
        { label: 'Dumka', state: 'Jharkhand (JH)' },
        { label: 'East Singhbhum', state: 'Jharkhand (JH)' },
        { label: 'Garhwa', state: 'Jharkhand (JH)' },
        { label: 'Giridih', state: 'Jharkhand (JH)' },
        { label: 'Godda', state: 'Jharkhand (JH)' },
        { label: 'Gumla', state: 'Jharkhand (JH)' },
        { label: 'Hazaribag', state: 'Jharkhand (JH)' },
        { label: 'Jamtara', state: 'Jharkhand (JH)' },
        { label: 'Khunti', state: 'Jharkhand (JH)' },
        { label: 'Koderma', state: 'Jharkhand (JH)' },
        { label: 'Latehar', state: 'Jharkhand (JH)' },
        { label: 'Lohardaga', state: 'Jharkhand (JH)' },
        { label: 'Pakur', state: 'Jharkhand (JH)' },
        { label: 'Palamu', state: 'Jharkhand (JH)' },
        { label: 'Ramgarh', state: 'Jharkhand (JH)' },
        { label: 'Ranchi', state: 'Jharkhand (JH)' },
        { label: 'Sahibganj', state: 'Jharkhand (JH)' },
        { label: 'Seraikela Kharsawan', state: 'Jharkhand (JH)' },
        { label: 'Simdega', state: 'Jharkhand (JH)' },
        { label: 'West Singhbhum', state: 'Jharkhand (JH)' },
        { label: 'Bagalkot', state: 'Karnataka (KA)' },
        { label: 'Bangalore Rural', state: 'Karnataka (KA)' },
        { label: 'Bangalore Urban', state: 'Karnataka (KA)' },
        { label: 'Belgaum', state: 'Karnataka (KA)' },
        { label: 'Bellary', state: 'Karnataka (KA)' },
        { label: 'Bidar', state: 'Karnataka (KA)' },
        { label: 'Bijapur', state: 'Karnataka (KA)' },
        { label: 'Chamarajnagar', state: 'Karnataka (KA)' },
        { label: 'Chikkamagaluru', state: 'Karnataka (KA)' },
        { label: 'Chikkaballapur', state: 'Karnataka (KA)' },
        { label: 'Chitradurga', state: 'Karnataka (KA)' },
        { label: 'Davanagere', state: 'Karnataka (KA)' },
        { label: 'Dharwad', state: 'Karnataka (KA)' },
        { label: 'Dakshina Kannada', state: 'Karnataka (KA)' },
        { label: 'Gadag', state: 'Karnataka (KA)' },
        { label: 'Gulbarga', state: 'Karnataka (KA)' },
        { label: 'Hassan', state: 'Karnataka (KA)' },
        { label: 'Haveri district', state: 'Karnataka (KA)' },
        { label: 'Kodagu', state: 'Karnataka (KA)' },
        { label: 'Kolar', state: 'Karnataka (KA)' },
        { label: 'Koppal', state: 'Karnataka (KA)' },
        { label: 'Mandya', state: 'Karnataka (KA)' },
        { label: 'Mysore', state: 'Karnataka (KA)' },
        { label: 'Raichur', state: 'Karnataka (KA)' },
        { label: 'Shimoga', state: 'Karnataka (KA)' },
        { label: 'Tumkur', state: 'Karnataka (KA)' },
        { label: 'Udupi', state: 'Karnataka (KA)' },
        { label: 'Uttara Kannada', state: 'Karnataka (KA)' },
        { label: 'Ramanagara', state: 'Karnataka (KA)' },
        { label: 'Yadgir', state: 'Karnataka (KA)' },
        { label: 'Alappuzha', state: 'Kerala (KL)' },
        { label: 'Ernakulam', state: 'Kerala (KL)' },
        { label: 'Idukki', state: 'Kerala (KL)' },
        { label: 'Kannur', state: 'Kerala (KL)' },
        { label: 'Kasaragod', state: 'Kerala (KL)' },
        { label: 'Kollam', state: 'Kerala (KL)' },
        { label: 'Kottayam', state: 'Kerala (KL)' },
        { label: 'Kozhikode', state: 'Kerala (KL)' },
        { label: 'Malappuram', state: 'Kerala (KL)' },
        { label: 'Palakkad', state: 'Kerala (KL)' },
        { label: 'Pathanamthitta', state: 'Kerala (KL)' },
        { label: 'Thrissur', state: 'Kerala (KL)' },
        { label: 'Thiruvananthapuram', state: 'Kerala (KL)' },
        { label: 'Wayanad', state: 'Kerala (KL)' },
        { label: 'Alirajpur', state: 'Madhya Pradesh (MP)' },
        { label: 'Anuppur', state: 'Madhya Pradesh (MP)' },
        { label: 'Ashok Nagar', state: 'Madhya Pradesh (MP)' },
        { label: 'Balaghat', state: 'Madhya Pradesh (MP)' },
        { label: 'Barwani', state: 'Madhya Pradesh (MP)' },
        { label: 'Betul', state: 'Madhya Pradesh (MP)' },
        { label: 'Bhind', state: 'Madhya Pradesh (MP)' },
        { label: 'Bhopal', state: 'Madhya Pradesh (MP)' },
        { label: 'Burhanpur', state: 'Madhya Pradesh (MP)' },
        { label: 'Chhatarpur', state: 'Madhya Pradesh (MP)' },
        { label: 'Chhindwara', state: 'Madhya Pradesh (MP)' },
        { label: 'Damoh', state: 'Madhya Pradesh (MP)' },
        { label: 'Datia', state: 'Madhya Pradesh (MP)' },
        { label: 'Dewas', state: 'Madhya Pradesh (MP)' },
        { label: 'Dhar', state: 'Madhya Pradesh (MP)' },
        { label: 'Dindori', state: 'Madhya Pradesh (MP)' },
        { label: 'Guna', state: 'Madhya Pradesh (MP)' },
        { label: 'Gwalior', state: 'Madhya Pradesh (MP)' },
        { label: 'Harda', state: 'Madhya Pradesh (MP)' },
        { label: 'Hoshangabad', state: 'Madhya Pradesh (MP)' },
        { label: 'Indore', state: 'Madhya Pradesh (MP)' },
        { label: 'Jabalpur', state: 'Madhya Pradesh (MP)' },
        { label: 'Jhabua', state: 'Madhya Pradesh (MP)' },
        { label: 'Katni', state: 'Madhya Pradesh (MP)' },
        { label: 'Khandwa (East Nimar)', state: 'Madhya Pradesh (MP)' },
        { label: 'Khargone (West Nimar)', state: 'Madhya Pradesh (MP)' },
        { label: 'Mandla', state: 'Madhya Pradesh (MP)' },
        { label: 'Mandsaur', state: 'Madhya Pradesh (MP)' },
        { label: 'Morena', state: 'Madhya Pradesh (MP)' },
        { label: 'Narsinghpur', state: 'Madhya Pradesh (MP)' },
        { label: 'Neemuch', state: 'Madhya Pradesh (MP)' },
        { label: 'Panna', state: 'Madhya Pradesh (MP)' },
        { label: 'Rewa', state: 'Madhya Pradesh (MP)' },
        { label: 'Rajgarh', state: 'Madhya Pradesh (MP)' },
        { label: 'Ratlam', state: 'Madhya Pradesh (MP)' },
        { label: 'Raisen', state: 'Madhya Pradesh (MP)' },
        { label: 'Sagar', state: 'Madhya Pradesh (MP)' },
        { label: 'Satna', state: 'Madhya Pradesh (MP)' },
        { label: 'Sehore', state: 'Madhya Pradesh (MP)' },
        { label: 'Seoni', state: 'Madhya Pradesh (MP)' },
        { label: 'Shahdol', state: 'Madhya Pradesh (MP)' },
        { label: 'Shajapur', state: 'Madhya Pradesh (MP)' },
        { label: 'Sheopur', state: 'Madhya Pradesh (MP)' },
        { label: 'Shivpuri', state: 'Madhya Pradesh (MP)' },
        { label: 'Sidhi', state: 'Madhya Pradesh (MP)' },
        { label: 'Tikamgarh', state: 'Madhya Pradesh (MP)' },
        { label: 'Ujjain', state: 'Madhya Pradesh (MP)' },
        { label: 'Umaria', state: 'Madhya Pradesh (MP)' },
        { label: 'Vidisha', state: 'Madhya Pradesh (MP)' },
        { label: 'Ahmednagar', state: 'Maharashtra (MH)' },
        { label: 'Akola', state: 'Maharashtra (MH)' },
        { label: 'Amravati', state: 'Maharashtra (MH)' },
        { label: 'Aurangabad', state: 'Maharashtra (MH)' },
        { label: 'Bhandara', state: 'Maharashtra (MH)' },
        { label: 'Beed', state: 'Maharashtra (MH)' },
        { label: 'Buldhana', state: 'Maharashtra (MH)' },
        { label: 'Chandrapur', state: 'Maharashtra (MH)' },
        { label: 'Dhule', state: 'Maharashtra (MH)' },
        { label: 'Gadchiroli', state: 'Maharashtra (MH)' },
        { label: 'Gondia', state: 'Maharashtra (MH)' },
        { label: 'Hingoli', state: 'Maharashtra (MH)' },
        { label: 'Jalgaon', state: 'Maharashtra (MH)' },
        { label: 'Jalna', state: 'Maharashtra (MH)' },
        { label: 'Kolhapur', state: 'Maharashtra (MH)' },
        { label: 'Latur', state: 'Maharashtra (MH)' },
        { label: 'Mumbai City', state: 'Maharashtra (MH)' },
        { label: 'Mumbai suburban', state: 'Maharashtra (MH)' },
        { label: 'Nandurbar', state: 'Maharashtra (MH)' },
        { label: 'Nanded', state: 'Maharashtra (MH)' },
        { label: 'Nagpur', state: 'Maharashtra (MH)' },
        { label: 'Nashik', state: 'Maharashtra (MH)' },
        { label: 'Osmanabad', state: 'Maharashtra (MH)' },
        { label: 'Parbhani', state: 'Maharashtra (MH)' },
        { label: 'Pune', state: 'Maharashtra (MH)' },
        { label: 'Raigad', state: 'Maharashtra (MH)' },
        { label: 'Ratnagiri', state: 'Maharashtra (MH)' },
        { label: 'Sindhudurg', state: 'Maharashtra (MH)' },
        { label: 'Sangli', state: 'Maharashtra (MH)' },
        { label: 'Solapur', state: 'Maharashtra (MH)' },
        { label: 'Satara', state: 'Maharashtra (MH)' },
        { label: 'Thane', state: 'Maharashtra (MH)' },
        { label: 'Wardha', state: 'Maharashtra (MH)' },
        { label: 'Washim', state: 'Maharashtra (MH)' },
        { label: 'Yavatmal', state: 'Maharashtra (MH)' },
        { label: 'Bishnupur', state: 'Manipur (MN)' },
        { label: 'Churachandpur', state: 'Manipur (MN)' },
        { label: 'Chandel', state: 'Manipur (MN)' },
        { label: 'Imphal East', state: 'Manipur (MN)' },
        { label: 'Senapati', state: 'Manipur (MN)' },
        { label: 'Tamenglong', state: 'Manipur (MN)' },
        { label: 'Thoubal', state: 'Manipur (MN)' },
        { label: 'Ukhrul', state: 'Manipur (MN)' },
        { label: 'Imphal West', state: 'Manipur (MN)' },
        { label: 'East Garo Hills', state: 'Meghalaya (ML)' },
        { label: 'East Khasi Hills', state: 'Meghalaya (ML)' },
        { label: 'Jaintia Hills', state: 'Meghalaya (ML)' },
        { label: 'Ri Bhoi', state: 'Meghalaya (ML)' },
        { label: 'South Garo Hills', state: 'Meghalaya (ML)' },
        { label: 'West Garo Hills', state: 'Meghalaya (ML)' },
        { label: 'West Khasi Hills', state: 'Meghalaya (ML)' },
        { label: 'Aizawl', state: 'Mizoram (MZ)' },
        { label: 'Champhai', state: 'Mizoram (MZ)' },
        { label: 'Kolasib', state: 'Mizoram (MZ)' },
        { label: 'Lawngtlai', state: 'Mizoram (MZ)' },
        { label: 'Lunglei', state: 'Mizoram (MZ)' },
        { label: 'Mamit', state: 'Mizoram (MZ)' },
        { label: 'Saiha', state: 'Mizoram (MZ)' },
        { label: 'Serchhip', state: 'Mizoram (MZ)' },
        { label: 'Nagaland', state: 'Nagaland (NL)' },
        { label: 'Dimapur', state: 'Nagaland (NL)' },
        { label: 'Kohima', state: 'Nagaland (NL)' },
        { label: 'Mokokchung', state: 'Nagaland (NL)' },
        { label: 'Mon', state: 'Nagaland (NL)' },
        { label: 'Phek', state: 'Nagaland (NL)' },
        { label: 'Tuensang', state: 'Nagaland (NL)' },
        { label: 'Wokha', state: 'Nagaland (NL)' },
        { label: 'Zunheboto', state: 'Nagaland (NL)' },
        { label: 'Angul', state: 'Orissa (OR)' },
        { label: 'Boudh (Bauda)', state: 'Orissa (OR)' },
        { label: 'Bhadrak', state: 'Orissa (OR)' },
        { label: 'Balangir', state: 'Orissa (OR)' },
        { label: 'Bargarh (Baragarh)', state: 'Orissa (OR)' },
        { label: 'Balasore', state: 'Orissa (OR)' },
        { label: 'Cuttack', state: 'Orissa (OR)' },
        { label: 'Debagarh (Deogarh)', state: 'Orissa (OR)' },
        { label: 'Dhenkanal', state: 'Orissa (OR)' },
        { label: 'Ganjam', state: 'Orissa (OR)' },
        { label: 'Gajapati', state: 'Orissa (OR)' },
        { label: 'Jharsuguda', state: 'Orissa (OR)' },
        { label: 'Jajpur', state: 'Orissa (OR)' },
        { label: 'Jagatsinghpur', state: 'Orissa (OR)' },
        { label: 'Khordha', state: 'Orissa (OR)' },
        { label: 'Kendujhar (Keonjhar)', state: 'Orissa (OR)' },
        { label: 'Kalahandi', state: 'Orissa (OR)' },
        { label: 'Kandhamal', state: 'Orissa (OR)' },
        { label: 'Koraput', state: 'Orissa (OR)' },
        { label: 'Kendrapara', state: 'Orissa (OR)' },
        { label: 'Malkangiri', state: 'Orissa (OR)' },
        { label: 'Mayurbhanj', state: 'Orissa (OR)' },
        { label: 'Nabarangpur', state: 'Orissa (OR)' },
        { label: 'Nuapada', state: 'Orissa (OR)' },
        { label: 'Nayagarh', state: 'Orissa (OR)' },
        { label: 'Puri', state: 'Orissa (OR)' },
        { label: 'Rayagada', state: 'Orissa (OR)' },
        { label: 'Sambalpur', state: 'Orissa (OR)' },
        { label: 'Subarnapur (Sonepur)', state: 'Orissa (OR)' },
        { label: 'Sundergarh', state: 'Orissa (OR)' },
        { label: 'Pondicherry', state: 'Puducherry (PY)' },
        { label: 'Karaikal', state: 'Puducherry (PY)' },
        { label: 'Mahe', state: 'Puducherry (PY)' },
        { label: 'Yanam', state: 'Puducherry (PY)' },
        { label: 'Amritsar', state: 'Punjab (PB)' },
        { label: 'Barnala', state: 'Punjab (PB)' },
        { label: 'Bathinda', state: 'Punjab (PB)' },
        { label: 'Firozpur', state: 'Punjab (PB)' },
        { label: 'Faridkot', state: 'Punjab (PB)' },
        { label: 'Fatehgarh Sahib', state: 'Punjab (PB)' },
        { label: 'Fazilka', state: 'Punjab (PB)' },
        { label: 'Gurdaspur', state: 'Punjab (PB)' },
        { label: 'Hoshiarpur', state: 'Punjab (PB)' },
        { label: 'Jalandhar', state: 'Punjab (PB)' },
        { label: 'Kapurthala', state: 'Punjab (PB)' },
        { label: 'Ludhiana', state: 'Punjab (PB)' },
        { label: 'Mansa', state: 'Punjab (PB)' },
        { label: 'Moga', state: 'Punjab (PB)' },
        { label: 'Sri Muktsar Sahib', state: 'Punjab (PB)' },
        { label: 'Pathankot', state: 'Punjab (PB)' },
        { label: 'Patiala', state: 'Punjab (PB)' },
        { label: 'Rupnagar', state: 'Punjab (PB)' },
        { label: 'Ajitgarh (Mohali)', state: 'Punjab (PB)' },
        { label: 'Sangrur', state: 'Punjab (PB)' },
        { label: 'Nawanshahr', state: 'Punjab (PB)' },
        { label: 'Tarn Taran', state: 'Punjab (PB)' },
        { label: 'Ajmer', state: 'Rajasthan (RJ)' },
        { label: 'Alwar', state: 'Rajasthan (RJ)' },
        { label: 'Bikaner', state: 'Rajasthan (RJ)' },
        { label: 'Barmer', state: 'Rajasthan (RJ)' },
        { label: 'Banswara', state: 'Rajasthan (RJ)' },
        { label: 'Bharatpur', state: 'Rajasthan (RJ)' },
        { label: 'Baran', state: 'Rajasthan (RJ)' },
        { label: 'Bundi', state: 'Rajasthan (RJ)' },
        { label: 'Bhilwara', state: 'Rajasthan (RJ)' },
        { label: 'Churu', state: 'Rajasthan (RJ)' },
        { label: 'Chittorgarh', state: 'Rajasthan (RJ)' },
        { label: 'Dausa', state: 'Rajasthan (RJ)' },
        { label: 'Dholpur', state: 'Rajasthan (RJ)' },
        { label: 'Dungapur', state: 'Rajasthan (RJ)' },
        { label: 'Ganganagar', state: 'Rajasthan (RJ)' },
        { label: 'Hanumangarh', state: 'Rajasthan (RJ)' },
        { label: 'Jhunjhunu', state: 'Rajasthan (RJ)' },
        { label: 'Jalore', state: 'Rajasthan (RJ)' },
        { label: 'Jodhpur', state: 'Rajasthan (RJ)' },
        { label: 'Jaipur', state: 'Rajasthan (RJ)' },
        { label: 'Jaisalmer', state: 'Rajasthan (RJ)' },
        { label: 'Jhalawar', state: 'Rajasthan (RJ)' },
        { label: 'Karauli', state: 'Rajasthan (RJ)' },
        { label: 'Kota', state: 'Rajasthan (RJ)' },
        { label: 'Nagaur', state: 'Rajasthan (RJ)' },
        { label: 'Pali', state: 'Rajasthan (RJ)' },
        { label: 'Pratapgarh', state: 'Rajasthan (RJ)' },
        { label: 'Rajsamand', state: 'Rajasthan (RJ)' },
        { label: 'Sikar', state: 'Rajasthan (RJ)' },
        { label: 'Sawai Madhopur', state: 'Rajasthan (RJ)' },
        { label: 'Sirohi', state: 'Rajasthan (RJ)' },
        { label: 'Tonk', state: 'Rajasthan (RJ)' },
        { label: 'Udaipur', state: 'Rajasthan (RJ)' },
        { label: 'East Sikkim', state: 'Sikkim (SK)' },
        { label: 'North Sikkim', state: 'Sikkim (SK)' },
        { label: 'South Sikkim', state: 'Sikkim (SK)' },
        { label: 'West Sikkim', state: 'Sikkim (SK)' },
        { label: 'Ariyalur', state: 'Tamil Nadu (TN)' },
        { label: 'Chennai', state: 'Tamil Nadu (TN)' },
        { label: 'Coimbatore', state: 'Tamil Nadu (TN)' },
        { label: 'Cuddalore', state: 'Tamil Nadu (TN)' },
        { label: 'Dharmapuri', state: 'Tamil Nadu (TN)' },
        { label: 'Dindigul', state: 'Tamil Nadu (TN)' },
        { label: 'Erode', state: 'Tamil Nadu (TN)' },
        { label: 'Kanchipuram', state: 'Tamil Nadu (TN)' },
        { label: 'Kanyakumari', state: 'Tamil Nadu (TN)' },
        { label: 'Karur', state: 'Tamil Nadu (TN)' },
        { label: 'Madurai', state: 'Tamil Nadu (TN)' },
        { label: 'Nagapattinam', state: 'Tamil Nadu (TN)' },
        { label: 'Nilgiris', state: 'Tamil Nadu (TN)' },
        { label: 'Namakkal', state: 'Tamil Nadu (TN)' },
        { label: 'Perambalur', state: 'Tamil Nadu (TN)' },
        { label: 'Pudukkottai', state: 'Tamil Nadu (TN)' },
        { label: 'Ramanathapuram', state: 'Tamil Nadu (TN)' },
        { label: 'Salem', state: 'Tamil Nadu (TN)' },
        { label: 'Sivaganga', state: 'Tamil Nadu (TN)' },
        { label: 'Tirupur', state: 'Tamil Nadu (TN)' },
        { label: 'Tiruchirappalli', state: 'Tamil Nadu (TN)' },
        { label: 'Theni', state: 'Tamil Nadu (TN)' },
        { label: 'Tirunelveli', state: 'Tamil Nadu (TN)' },
        { label: 'Thanjavur', state: 'Tamil Nadu (TN)' },
        { label: 'Thoothukudi', state: 'Tamil Nadu (TN)' },
        { label: 'Tiruvallur', state: 'Tamil Nadu (TN)' },
        { label: 'Tiruvarur', state: 'Tamil Nadu (TN)' },
        { label: 'Tiruvannamalai', state: 'Tamil Nadu (TN)' },
        { label: 'Vellore', state: 'Tamil Nadu (TN)' },
        { label: 'Viluppuram', state: 'Tamil Nadu (TN)' },
        { label: 'Virudhunagar', state: 'Tamil Nadu (TN)' },
        { label: 'Karimnagar', state: 'Telangana' },
        { label: 'Khammam', state: 'Telangana' },
        { label: 'Mahbubnagar', state: 'Telangana' },
        { label: 'Nizamabad', state: 'Telangana' },
        { label: 'Hyderabad', state: 'Telangana' },
        { label: 'Warangal', state: 'Telangana' },
        { label: 'Sangareddi', state: 'Telangana' },
        { label: 'Dhalai', state: 'Tripura (TR)' },
        { label: 'North Tripura', state: 'Tripura (TR)' },
        { label: 'South Tripura', state: 'Tripura (TR)' },
        { label: 'Khowai', state: 'Tripura (TR)' },
        { label: 'West Tripura', state: 'Tripura (TR)' },
        { label: 'Agra', state: 'Uttar Pradesh (UP)' },
        { label: 'Allahabad', state: 'Uttar Pradesh (UP)' },
        { label: 'Aligarh', state: 'Uttar Pradesh (UP)' },
        { label: 'Ambedkar Nagar', state: 'Uttar Pradesh (UP)' },
        { label: 'Auraiya', state: 'Uttar Pradesh (UP)' },
        { label: 'Azamgarh', state: 'Uttar Pradesh (UP)' },
        { label: 'Barabanki', state: 'Uttar Pradesh (UP)' },
        { label: 'Budaun', state: 'Uttar Pradesh (UP)' },
        { label: 'Bagpat', state: 'Uttar Pradesh (UP)' },
        { label: 'Bahraich', state: 'Uttar Pradesh (UP)' },
        { label: 'Bijnor', state: 'Uttar Pradesh (UP)' },
        { label: 'Ballia', state: 'Uttar Pradesh (UP)' },
        { label: 'Banda', state: 'Uttar Pradesh (UP)' },
        { label: 'Balrampur', state: 'Uttar Pradesh (UP)' },
        { label: 'Bareilly', state: 'Uttar Pradesh (UP)' },
        { label: 'Basti', state: 'Uttar Pradesh (UP)' },
        { label: 'Bulandshahr', state: 'Uttar Pradesh (UP)' },
        { label: 'Chandauli', state: 'Uttar Pradesh (UP)' },
        { label: 'Chhatrapati Shahuji Maharaj Nagar', state: 'Uttar Pradesh (UP)' },
        { label: 'Chitrakoot', state: 'Uttar Pradesh (UP)' },
        { label: 'Deoria', state: 'Uttar Pradesh (UP)' },
        { label: 'Etah', state: 'Uttar Pradesh (UP)' },
        { label: 'Kanshi Ram Nagar', state: 'Uttar Pradesh (UP)' },
        { label: 'Etawah', state: 'Uttar Pradesh (UP)' },
        { label: 'Firozabad', state: 'Uttar Pradesh (UP)' },
        { label: 'Farrukhabad', state: 'Uttar Pradesh (UP)' },
        { label: 'Fatehpur', state: 'Uttar Pradesh (UP)' },
        { label: 'Faizabad', state: 'Uttar Pradesh (UP)' },
        { label: 'Gautam Buddh Nagar', state: 'Uttar Pradesh (UP)' },
        { label: 'Gonda', state: 'Uttar Pradesh (UP)' },
        { label: 'Ghazipur', state: 'Uttar Pradesh (UP)' },
        { label: 'Gorakhpur', state: 'Uttar Pradesh (UP)' },
        { label: 'Ghaziabad', state: 'Uttar Pradesh (UP)' },
        { label: 'Hamirpur', state: 'Uttar Pradesh (UP)' },
        { label: 'Hardoi', state: 'Uttar Pradesh (UP)' },
        { label: 'Mahamaya Nagar', state: 'Uttar Pradesh (UP)' },
        { label: 'Jhansi', state: 'Uttar Pradesh (UP)' },
        { label: 'Jalaun', state: 'Uttar Pradesh (UP)' },
        { label: 'Jyotiba Phule Nagar', state: 'Uttar Pradesh (UP)' },
        { label: 'Jaunpur district', state: 'Uttar Pradesh (UP)' },
        { label: 'Ramabai Nagar (Kanpur Dehat)', state: 'Uttar Pradesh (UP)' },
        { label: 'Kannauj', state: 'Uttar Pradesh (UP)' },
        { label: 'Kanpur', state: 'Uttar Pradesh (UP)' },
        { label: 'Kaushambi', state: 'Uttar Pradesh (UP)' },
        { label: 'Kushinagar', state: 'Uttar Pradesh (UP)' },
        { label: 'Lalitpur', state: 'Uttar Pradesh (UP)' },
        { label: 'Lakhimpur Kheri', state: 'Uttar Pradesh (UP)' },
        { label: 'Lucknow', state: 'Uttar Pradesh (UP)' },
        { label: 'Mau', state: 'Uttar Pradesh (UP)' },
        { label: 'Meerut', state: 'Uttar Pradesh (UP)' },
        { label: 'Maharajganj', state: 'Uttar Pradesh (UP)' },
        { label: 'Mahoba', state: 'Uttar Pradesh (UP)' },
        { label: 'Mirzapur', state: 'Uttar Pradesh (UP)' },
        { label: 'Moradabad', state: 'Uttar Pradesh (UP)' },
        { label: 'Mainpuri', state: 'Uttar Pradesh (UP)' },
        { label: 'Mathura', state: 'Uttar Pradesh (UP)' },
        { label: 'Muzaffarnagar', state: 'Uttar Pradesh (UP)' },
        { label: 'Panchsheel Nagar district (Hapur)', state: 'Uttar Pradesh (UP)' },
        { label: 'Shamli', state: 'Uttar Pradesh (UP)' },
        { label: 'Pratapgarh', state: 'Uttar Pradesh (UP)' },
        { label: 'Rampur', state: 'Uttar Pradesh (UP)' },
        { label: 'Raebareli', state: 'Uttar Pradesh (UP)' },
        { label: 'Saharanpur', state: 'Uttar Pradesh (UP)' },
        { label: 'Sitapur', state: 'Uttar Pradesh (UP)' },
        { label: 'Shahjahanpur', state: 'Uttar Pradesh (UP)' },
        { label: 'Sant Kabir Nagar', state: 'Uttar Pradesh (UP)' },
        { label: 'Siddharthnagar', state: 'Uttar Pradesh (UP)' },
        { label: 'Sonbhadra', state: 'Uttar Pradesh (UP)' },
        { label: 'Sant Ravidas Nagar', state: 'Uttar Pradesh (UP)' },
        { label: 'Sultanpur', state: 'Uttar Pradesh (UP)' },
        { label: 'Shravasti', state: 'Uttar Pradesh (UP)' },
        { label: 'Unnao', state: 'Uttar Pradesh (UP)' },
        { label: 'Varanasi', state: 'Uttar Pradesh (UP)' },
        { label: 'Almora', state: 'Uttarakhand (UK)' },
        { label: 'Bageshwar', state: 'Uttarakhand (UK)' },
        { label: 'Chamoli', state: 'Uttarakhand (UK)' },
        { label: 'Champawat', state: 'Uttarakhand (UK)' },
        { label: 'Dehradun', state: 'Uttarakhand (UK)' },
        { label: 'Haridwar', state: 'Uttarakhand (UK)' },
        { label: 'Nainital', state: 'Uttarakhand (UK)' },
        { label: 'Pauri Garhwal', state: 'Uttarakhand (UK)' },
        { label: 'Pithoragarh', state: 'Uttarakhand (UK)' },
        { label: 'Rudraprayag', state: 'Uttarakhand (UK)' },
        { label: 'Tehri Garhwal', state: 'Uttarakhand (UK)' },
        { label: 'Udham Singh Nagar', state: 'Uttarakhand (UK)' },
        { label: 'Uttarkashi', state: 'Uttarakhand (UK)' },
        { label: 'Birbhum', state: 'West Bengal (WB)' },
        { label: 'Bankura', state: 'West Bengal (WB)' },
        { label: 'Bardhaman', state: 'West Bengal (WB)' },
        { label: 'Darjeeling', state: 'West Bengal (WB)' },
        { label: 'Dakshin Dinajpur', state: 'West Bengal (WB)' },
        { label: 'Hooghly', state: 'West Bengal (WB)' },
        { label: 'Howrah', state: 'West Bengal (WB)' },
        { label: 'Jalpaiguri', state: 'West Bengal (WB)' },
        { label: 'Cooch Behar', state: 'West Bengal (WB)' },
        { label: 'Kolkata', state: 'West Bengal (WB)' },
        { label: 'Maldah', state: 'West Bengal (WB)' },
        { label: 'Paschim Medinipur', state: 'West Bengal (WB)' },
        { label: 'Purba Medinipur', state: 'West Bengal (WB)' },
        { label: 'Murshidabad', state: 'West Bengal (WB)' },
        { label: 'Nadia', state: 'West Bengal (WB)' },
        { label: 'North 24 Parganas', state: 'West Bengal (WB)' },
        { label: 'South 24 Parganas', state: 'West Bengal (WB)' },
        { label: 'Purulia', state: 'West Bengal (WB)' },
        { label: 'Uttar Dinajpur', state: 'West Bengal (WB)' }
];